// 构建脚本：把 plugin/host.js、plugin/client.js 与核心脚本打包成
// Cordis 动态插件可执行的单段字符串（函数体形态）。
// 运行方式：node build.js
//
// 产物：
//   dist/host-bundle.js    — Host 代码（已把 scripts/update-cli-tools.js
//                            以字符串形式内嵌，替换 __UPDATE_SCRIPT__ 占位符）
//   dist/client-bundle.js  — Client 代码（结果卡片）

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const HEADER = '// AUTO-GENERATED BY build.js - DO NOT EDIT\n';

// 去注释：块注释、行首 // 注释、多余空行（不触碰字符串内的 //，
// 因为只匹配行首的 //）
function strip(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^[ \t]*\/\/.*$/gm, '')
    .replace(/\n{3,}/g, '\n\n');
}

function read(p) {
  return readFileSync(resolve(__dirname, p), 'utf8');
}

function buildHostBundle() {
  const hostSrc = strip(read('plugin/host.js'));
  const coreSrc = strip(read('scripts/update-cli-tools.js'));

  const placeholder = '__UPDATE_SCRIPT__';
  const count = hostSrc.split(placeholder).length - 1;
  if (count !== 1) {
    throw new Error('plugin/host.js 中 __UPDATE_SCRIPT__ 占位符应恰好出现 1 次，实际 ' + count + ' 次');
  }

  // 用函数形式替换，避免 JSON 字符串里的 $ 序列被 replace 解释
  const embedded = JSON.stringify(coreSrc);
  console.log('  ✓ 内嵌核心脚本:', embedded.length, 'chars');

  return HEADER + '// foxai_cli_update Host Bundle（含内嵌 update-cli-tools.js）\n' +
    hostSrc.replace(placeholder, () => embedded);
}

function buildClientBundle() {
  return HEADER + '// foxai_cli_update Client Bundle（结果卡片）\n' + strip(read('plugin/client.js'));
}

function main() {
  mkdirSync(resolve(__dirname, 'dist'), { recursive: true });
  const host = buildHostBundle();
  const client = buildClientBundle();
  writeFileSync(resolve(__dirname, 'dist/host-bundle.js'), host, 'utf8');
  writeFileSync(resolve(__dirname, 'dist/client-bundle.js'), client, 'utf8');
  console.log('✓ 已生成 dist/host-bundle.js (' + host.length + ' chars) 与 dist/client-bundle.js (' + client.length + ' chars)');

  // 语法自检：两段代码都是「函数体」，用 new Function 解析（不执行）
  new Function('harness', 'ctx', host);
  new Function('ctx', 'React', 'host', 'styles', client);
  console.log('✓ 语法自检通过（new Function 解析 host/client 函数体）');
}

main();
